"""Persistent UI settings for the ViralCutter WebUI.

The WebUI used to require re-entering the Gemini API key (and model /
chunk size / backend) on every run and every restart. This module lets the
UI read and write the same `api_config.json` the CLI already uses, so a
key saved once is remembered forever — no more retyping it each session.

Design:
  * `load_ui_settings()`  — reads the merged config exactly like the CLI
    (`scripts.secure_config.load_api_config`): env var wins, then the
    encrypted store, then legacy plaintext api_config.json.
  * `save_ui_settings()`  — atomically writes api_config.json (temp file +
    rename), preserving the selected backend / model / chunk size.
  * `mask_key()`          — safe display (AIza…XXXX) for status cards.
  * `test_gemini_connection()` — validates a key right in the UI instead of
    failing mid-processing ("think outside the box": instant feedback).

No gradio imports — pure and unit-testable.
"""
import json
import os
import sys

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from scripts.secure_config import legacy_config_path, load_api_config

# Local UI-preferences file (user-machine state, NOT tracked by git).
WEBUI_PREFS_FILE = "webui_settings.json"

# Fields the WebUI persists. Keys match api_config.json.
PERSISTED_KEYS = ("ai_backend", "ai_model", "chunk_size")

KEY_SOURCE_ENV = "env"
KEY_SOURCE_SECURE = "secure"
KEY_SOURCE_FILE = "file"
KEY_SOURCE_NONE = "none"

# Gemini keys are generated by AI Studio and always start with this prefix.
GEMINI_KEY_PREFIX = "AIza"

# placeholders that mean "no real key" in api_config.json
FAKE_KEYS = {"", "SUA_KEY_AQUI", "YOUR_KEY_HERE"}
VALID_BACKENDS = {"gemini", "g4f", "local", "manual"}
MIN_CHUNK_SIZE = 1
MAX_CHUNK_SIZE = 200000


def _coerce_chunk(value, default):
    try:
        return max(MIN_CHUNK_SIZE, min(MAX_CHUNK_SIZE, int(value)))
    except (TypeError, ValueError, OverflowError):
        return int(default)


def _defaults():
    return {
        "selected_api": "gemini",
        "gemini": {
            "api_key": "",
            "api_keys": [],
            "key_mode": "auto",
            "model": "gemini-2.5-flash-lite-preview-09-2025",
            "chunk_size": 20000,
        },
        "g4f": {"model": "gpt-4o-mini", "chunk_size": 2000},
    }


def load_ui_settings(base_dir=None):
    """Resolve the settings the WebUI should show.

    Returns dict:
      ai_backend  — "gemini" | "g4f" | "local" | "manual"
      api_key     — resolved key ("" when none)
      key_source  — "env" | "secure" | "file" | "none"
      ai_model    — model name for the selected backend
      chunk_size  — chunk size for the selected backend
    """
    config = load_api_config(base_dir) or _defaults()
    if not isinstance(config, dict):
        config = _defaults()
    backend = config.get("selected_api") or "gemini"
    if backend not in VALID_BACKENDS:
        backend = "gemini"
    gemini = config.get("gemini") or {}
    if not isinstance(gemini, dict):
        gemini = {}

    # Resolve up to three keys in the same priority order as the CLI.
    from scripts.secure_config import resolve_api_keys as _resolve_keys
    keys = []
    source = KEY_SOURCE_NONE
    env_keys = _resolve_keys(base_dir=base_dir, warn=False) if os.getenv("VIRALCUTTER_GEMINI_KEYS") or os.getenv("VIRALCUTTER_GEMINI_KEY") or os.getenv("GEMINI_API_KEY") else []
    if env_keys:
        keys, source = env_keys, KEY_SOURCE_ENV
    else:
        from scripts.secure_config import get_keys as _secure_get_keys
        try:
            keys = _secure_get_keys(base_dir=base_dir)
        except Exception:
            keys = []
        if keys:
            source = KEY_SOURCE_SECURE
    if not keys:
        file_keys = gemini.get("api_keys") or [gemini.get("api_key", "")]
        keys = [str(item).strip() for item in file_keys if str(item or "").strip() not in FAKE_KEYS][:3]
        if keys:
            source = KEY_SOURCE_FILE
    key = keys[0] if keys else ""

    backend_cfg = gemini if backend == "gemini" else (config.get("g4f") or {})
    if not isinstance(backend_cfg, dict):
        backend_cfg = {}
    model = backend_cfg.get("model") or gemini.get("model") or ""
    default_chunk = 20000 if backend == "gemini" else 2000
    chunk = _coerce_chunk(backend_cfg.get("chunk_size"), default_chunk)

    return {
        "ai_backend": backend,
        "api_key": key,
        "api_keys": keys,
        "key_mode": str(gemini.get("key_mode") or "auto") if str(gemini.get("key_mode") or "auto") in {"auto", "1", "2", "3"} else "auto",
        "key_source": source,
        "ai_model": model,
        "chunk_size": chunk,
    }


def save_ui_settings(ai_backend=None, api_key=None, ai_model=None, chunk_size=None,
                     base_dir=None, api_keys=None, key_mode=None):
    """Persist the UI's AI settings to api_config.json (atomic write).

    Explicitly does NOT persist the key when it came from an environment
    variable (env stays the source of truth and the file stays clean).

    Returns (ok, message) — message is human-readable (Arabic) so the UI
    can show it directly.
    """
    path = legacy_config_path(base_dir)
    config = _defaults()
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                loaded = json.load(f)
            if isinstance(loaded, dict):
                config.update(loaded)
        except Exception:
            pass
    for section in ("gemini", "g4f"):
        if not isinstance(config.get(section), dict):
            config[section] = {}

    env_keys = []
    from scripts.secure_config import resolve_api_keys as _resolve_keys
    if os.getenv("VIRALCUTTER_GEMINI_KEYS") or os.getenv("VIRALCUTTER_GEMINI_KEY") or os.getenv("GEMINI_API_KEY"):
        env_keys = _resolve_keys(base_dir=base_dir, warn=False)
    if ai_backend in VALID_BACKENDS:
        config["selected_api"] = ai_backend
    if config.get("selected_api") not in VALID_BACKENDS:
        config["selected_api"] = "gemini"
    backend = config["selected_api"]

    supplied_keys = api_keys if api_keys is not None else ([api_key] if api_key else [])
    clean_keys = []
    for value in supplied_keys or []:
        value = str(value or "").strip()
        if value and value not in FAKE_KEYS and value not in clean_keys:
            clean_keys.append(value)
        if len(clean_keys) >= 3:
            break
    if clean_keys and not env_keys:
        config["gemini"]["api_keys"] = clean_keys
        config["gemini"]["api_key"] = clean_keys[0]
    elif not isinstance(config["gemini"].get("api_keys"), list):
        legacy_key = str(config["gemini"].get("api_key") or "").strip()
        config["gemini"]["api_keys"] = [legacy_key] if legacy_key and legacy_key not in FAKE_KEYS else []

    if key_mode in {"auto", "1", "2", "3"}:
        config["gemini"]["key_mode"] = key_mode

    if ai_model:
        section = config["gemini"] if backend == "gemini" else config["g4f"]
        section["model"] = ai_model
    if chunk_size is not None:
        section = config["gemini"] if backend == "gemini" else config["g4f"]
        default_chunk = 20000 if backend == "gemini" else 2000
        section["chunk_size"] = _coerce_chunk(chunk_size, default_chunk)

    # SECURITY: when a passphrase is configured, keep the API key OUT of the
    # plaintext api_config.json and store it in the encrypted store instead.
    passphrase = os.environ.get("VIRALCUTTER_CONFIG_PASSPHRASE", "").strip()
    stored_keys = config["gemini"].get("api_keys") or []
    if stored_keys and passphrase:
        try:
            from scripts.secure_config import set_keys
            set_keys(stored_keys, passphrase=passphrase, base_dir=base_dir)
            config["gemini"]["api_key"] = ""
            config["gemini"]["api_keys"] = []  # plaintext file stays clean
        except Exception as e:
            print("[settings-store] WARNING: encrypted key storage failed "
                  "({}); falling back to plaintext api_config.json.".format(e))

    try:
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(config, f, ensure_ascii=False, indent=4)
            f.write("\n")
            f.flush()
            os.fsync(f.fileno())
        os.replace(tmp, path)
        return True, ""
    except Exception as e:
        return False, str(e)


def mask_key(key, visible_head=4, visible_tail=4):
    """Mask a key for display: AIza****wxyz (short keys fully masked)."""
    key = (key or "").strip()
    if not key:
        return ""
    if len(key) <= visible_head + visible_tail + 4:
        return key[:visible_head] + "*" * 4 + key[-2:]
    return key[:visible_head] + "*" * 8 + key[-visible_tail:]


def looks_like_gemini_key(key):
    """Heuristic guard: Gemini keys are ~39 chars and start with AIza."""
    key = (key or "").strip()
    if not key:
        return False
    return key.startswith(GEMINI_KEY_PREFIX)


def _rest_test_gemini(api_key, timeout=10):
    """Fallback REST check — no SDK needed. Returns (ok, detail)."""
    import json as _json
    import urllib.error
    import urllib.request

    url = "https://generativelanguage.googleapis.com/v1beta/models?key={}".format(
        api_key.strip())
    req = urllib.request.Request(url, headers={"User-Agent": "ViralCutter/1.0"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            data = _json.loads(resp.read().decode("utf-8", "replace"))
            models = data.get("models", [])
            return True, "{} models".format(len(models))
    except urllib.error.HTTPError as e:
        body = ""
        try:
            body = e.read().decode("utf-8", "replace")[:300]
        except Exception:
            pass
        return False, "HTTP {}: {}".format(e.code, body)
    except Exception as e:
        return False, str(e)


def test_gemini_connection(api_key, model_name="gemini-2.5-flash", timeout=10):
    """Validate a Gemini API key. Returns (ok, message).

    Uses the installed Google SDK when available, otherwise the REST
    endpoint. Never raises.
    """
    key = (api_key or "").strip()
    if not key:
        return False, "Gemini API key is empty"
    try:
        import importlib
        try:
            client = importlib.import_module("google.genai").Client(api_key=key)
            resp = client.models.generate_content(
                model=model_name, contents="Reply with exactly: ok",
                config={"http_options": {"timeout": timeout * 1000}})
            return True, (getattr(resp, "text", "") or "").strip()
        except ImportError:
            try:
                genai = importlib.import_module("google.generativeai")  # legacy SDK
                genai.configure(api_key=key)
                model = genai.GenerativeModel(model_name)
                resp = model.generate_content("Reply with exactly: ok", request_options={"timeout": timeout})
                text = getattr(resp, "text", "") or ""
                return True, text.strip()
            except ImportError:
                return _rest_test_gemini(key, timeout)
    except Exception as e:
        err = str(e)
        # translate the common SDK errors into something the UI can show
        if "API key not valid" in err or "API_KEY_INVALID" in err:
            return False, "API key not valid"
        if "quota" in err.lower() or "RESOURCE_EXHAUSTED" in err:
            return False, "quota exceeded"
        if "PERMISSION_DENIED" in err:
            return False, "permission denied"
        return False, err


# ---------------------------------------------------------------------------
# Full WebUI preferences (v6.9.2) — remember EVERY form field, not just the
# API key. Same spirit as the headline v6.9 feature: set it once, it stays.
# ---------------------------------------------------------------------------

def webui_prefs_path(base_dir=None):
    """Path of the local prefs file (default: repo root)."""
    return os.path.join(base_dir or _repo_root(), WEBUI_PREFS_FILE)


def _repo_root():
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def load_webui_prefs(base_dir=None):
    """All saved WebUI form preferences ({} when none / corrupt)."""
    path = webui_prefs_path(base_dir)
    if not os.path.exists(path):
        return {}
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def save_webui_prefs(prefs, base_dir=None):
    """Persist form preferences atomically. Returns (ok, error_msg)."""
    prefs = {k: v for k, v in (prefs or {}).items() if v is not None}
    path = webui_prefs_path(base_dir)
    try:
        tmp = path + ".tmp"
        with open(tmp, "w", encoding="utf-8") as f:
            json.dump(prefs, f, ensure_ascii=False, indent=2)
        os.replace(tmp, path)
        return True, ""
    except Exception as e:
        return False, str(e)
